name: Build Android APK
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 使用 Docker 方式，环境是现成的，不需要现场安装几百兆的软件
      # 这能极大减少卡顿和出错的概率
      - name: Build with Buildozer (Docker)
        uses: docker://kivy/buildozer:latest
        env:
          BUILDOZER_WARN_ON_ROOT: 0
        with:
          args: android debug

      # 这里的权限修复很重要，因为 Docker 可能会把文件所有者改成 root
      - name: Fix Permissions
        if: always()
        run: sudo chown -R $USER:$USER .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk